# Generated by Django 5.1.3 on 2025-01-08 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueNumberCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BlossomFilterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blossom_filter', models.JSONField()),
                ('unique_number_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uniquenumbercount')),
            ],
        ),
    ]
